/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog.loading;

import view.dialog.*;

/**
 * Dialog to show the help
 * 
 * @author zenbook
 */
public class LoadingDialog extends BaseDialog implements IGuiLoading{

    public enum LoadingState {BACKGROUND, DONE, CANCEL};
    
    private LoadingState state;
    
    /**
     * Creates new form AboutDialog
     * @param parent
     * @param modal
     * @param title
     */
    public LoadingDialog(java.awt.Frame parent, boolean modal, String title) {
        super(parent, modal);
        this.title.setText(title);
    }

    @Override
    public void loading(LoadingImplements l) {
        LoadingImplements.updateLoading(loadingbar, loadingstat, l);
        if(l.progress == 100) {
            state = LoadingState.DONE;
            this.dispose();
        }
    }
    
    public LoadingState getState() {
        return state;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        cancel_btn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        loadingstat = new javax.swing.JLabel();
        background_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading...");
        setResizable(false);

        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/Stop16.gif"))); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        title.setText("Title");

        loadingstat.setText(" Calculating time remaining...");

        background_btn.setText("Background");
        background_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                background_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadingbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(background_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(loadingstat))
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingbar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingstat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn)
                    .addComponent(background_btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        state = LoadingState.CANCEL;
        this.dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void background_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_background_btnActionPerformed
        state = LoadingState.BACKGROUND;
        this.dispose();
    }//GEN-LAST:event_background_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton background_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingstat;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
