\echo Borrant taula de fets
DROP TABLE IF EXISTS Botiga CASCADE;
DROP TABLE IF EXISTS Edat CASCADE;
DROP TABLE IF EXISTS Usuari CASCADE;
DROP TABLE IF EXISTS Pagament CASCADE;
DROP TABLE IF EXISTS Campanya CASCADE;
DROP TABLE IF EXISTS Talla CASCADE;
DROP TABLE IF EXISTS Color CASCADE;
DROP TABLE IF EXISTS Familia CASCADE;
DROP TABLE IF EXISTS Marca CASCADE;
DROP TABLE IF EXISTS Producte CASCADE;
DROP TABLE IF EXISTS Data CASCADE;
DROP TABLE IF EXISTS Fets CASCADE;
--DROP TABLE IF EXISTS Data CASCADE;
\echo Taula de fets borrada
