/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.player.IPlayer;
import model.config.DirectionType;

/**
 *
 * @author zenbook
 */
public class OptionsDialog extends javax.swing.JDialog {

    private IPlayer player;
    
    /**
     * Creates new form OptionsDialog
     * @param parent
     * @param modal
     * @param player
     */
    public OptionsDialog(java.awt.Frame parent, boolean modal, IPlayer player) {
        super(parent, modal);
        initComponents();
        
        this.player =  player;
        
        slider.setValue(player.getFrameRate());
        fpslabel.setText(player.getFrameRate()+"");
        
        if(player.getDirection() == DirectionType.FORWARD) {
            forwardrb.setSelected(true);
        } else{
            backwardrb.setSelected(true);
        }
        
        //player.setFrameRate(slider.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        frameratelabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        slider = new javax.swing.JSlider();
        directionlabel = new javax.swing.JLabel();
        forwardrb = new javax.swing.JRadioButton();
        backwardrb = new javax.swing.JRadioButton();
        cancelbtn = new javax.swing.JButton();
        fpslabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        frameratelabel.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        frameratelabel.setText("Frame Rate (fps)");

        slider.setMinimum(1);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        slider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        directionlabel.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        directionlabel.setText("Direction");

        buttonGroup1.add(forwardrb);
        forwardrb.setText("Forward");
        forwardrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardrbActionPerformed(evt);
            }
        });

        buttonGroup1.add(backwardrb);
        backwardrb.setText("Backward");
        backwardrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardrbActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        fpslabel.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backwardrb)
                            .addComponent(forwardrb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frameratelabel)
                            .addComponent(directionlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fpslabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameratelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpslabel))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(directionlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forwardrb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backwardrb))
                    .addComponent(cancelbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forwardrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardrbActionPerformed
        player.setDirection(DirectionType.FORWARD);
    }//GEN-LAST:event_forwardrbActionPerformed

    private void backwardrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardrbActionPerformed
        player.setDirection(DirectionType.BACKWARD);
    }//GEN-LAST:event_backwardrbActionPerformed

    private void sliderCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sliderCaretPositionChanged
        
    }//GEN-LAST:event_sliderCaretPositionChanged

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        player.setFrameRate(slider.getValue());
        fpslabel.setText(slider.getValue()+"");
    }//GEN-LAST:event_sliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton backwardrb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel directionlabel;
    private javax.swing.JRadioButton forwardrb;
    private javax.swing.JLabel fpslabel;
    private javax.swing.JLabel frameratelabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
